# Development Dockerfile
FROM node:22-alpine

WORKDIR /usr/src/app

# Instalar dependências do sistema necessárias para o Prisma
RUN apk add --no-cache openssl

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar todas as dependências
RUN npm install

# Copiar o resto do código
COPY . .